#spring.application.name=ci
spring:
  application:
    name: ci-server
  datasource:
    url: jdbc:mysql://mysql:3306/ms
    #    ?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create