spring:
  application:
    name: ci-server
  datasource:
    url: jdbc:mysql://localhost:3306/boards?&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create