#spring.application.name=ci
spring:
  application:
    name: ci-server
  datasource:
    url: jdbc:mysql://10.128.0.6:3308/ms?&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create