#spring.application.name=ci
spring:
  application:
    name: ci-server
  datasource:
    url: jdbc:mysql://board-mysql:3306/boards?&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create