#spring.application.name=ci
spring:
  application:
    name: ci-server
  datasource:
    url: jdbc:mysql://10.128.0.7:3308/boards?&serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: create